import { normalizeLanguage } from '../../i18n/language';

const homeCopy = {
  'zh-CN': {
    heroAria: 'Kcode 首页',
    heroTitle: '一个接口，无限模型',
    heroSubtitle: '一站式对接各种大模型。让开发更智能、更高效。',
    docs: '文档',
    primaryCta: '立即体验',
    featuresAria: '核心能力',
    featureCoverageTitle: '主流模型全覆盖',
    voice: '语音生成',
    video: '视频生成',
    rerank: '重排序',
    featureApiTitle: '统一接口，模型轻松切',
    featureRoutingTitle: '无限并发，永远在线',
    autoRoute: '自动路由',
    ecosystemTitle: '构建 AI 共赢生态',
    ecosystemSubtitle: '精选生态伙伴应用，立享所有模型 10% 优惠 - 持续接入中，欢迎成为下一个！',
    partners: ['帆软软件', 'Cherry Studio', 'HelpKnow', 'NextChat', 'LobeHub'],
    discountLine1: '获取 10%',
    discountLine2: '优惠',
    morePanels: [
      {
        title: '主流模型，一站接入',
        text: '兼容 OpenAI、Anthropic、Gemini 风格接口',
        link: '查看模型',
      },
      {
        title: '稳定路由，自动切换',
        text: '聚合多家上游供应商，按可用性与策略自动分发请求，降低接入和运维成本。',
        link: '进入 Playground',
      },
      {
        title: '应用生态，开箱即用',
        text: '对接常见客户端与开发工具，用同一个 Key 管理不同场景的模型调用。',
        link: '了解生态',
      },
    ],
    footerTagline: 'One Interface, Router All Models.',
    notice: '公告',
  },
  'zh-TW': {
    heroAria: 'Kcode 首頁',
    heroTitle: '一個介面，無限模型',
    heroSubtitle: '一站式對接各種大模型。讓開發更智慧、更高效。',
    docs: '文件',
    primaryCta: '立即體驗',
    featuresAria: '核心能力',
    featureCoverageTitle: '主流模型全覆蓋',
    voice: '語音生成',
    video: '影片生成',
    rerank: '重排序',
    featureApiTitle: '統一介面，模型輕鬆切換',
    featureRoutingTitle: '無限併發，永遠在線',
    autoRoute: '自動路由',
    ecosystemTitle: '構建 AI 共贏生態',
    ecosystemSubtitle: '精選生態夥伴應用，立享所有模型 10% 優惠 - 持續接入中，歡迎成為下一位！',
    partners: ['帆軟軟體', 'Cherry Studio', 'HelpKnow', 'NextChat', 'LobeHub'],
    discountLine1: '取得 10%',
    discountLine2: '優惠',
    morePanels: [
      {
        title: '主流模型，一站接入',
        text: '相容 OpenAI 風格介面，支援文字、視覺、語音、影片、嵌入、重排等常用能力。',
        link: '查看模型',
      },
      {
        title: '穩定路由，自動切換',
        text: '聚合多家上游供應商，按可用性與策略自動分發請求，降低接入和維運成本。',
        link: '進入 Playground',
      },
      {
        title: '應用生態，開箱即用',
        text: '對接常見客戶端與開發工具，用同一個 Key 管理不同場景的模型調用。',
        link: '了解生態',
      },
    ],
    footerTagline: 'One Interface, Router All Models.',
    notice: '公告',
  },
  en: {
    heroAria: 'Kcode homepage',
    heroTitle: 'One API, unlimited models',
    heroSubtitle: 'Connect to leading AI models in one place. Build smarter and ship faster.',
    docs: 'Docs',
    primaryCta: 'Start now',
    featuresAria: 'Core capabilities',
    featureCoverageTitle: 'Mainstream model coverage',
    voice: 'Voice generation',
    video: 'Video generation',
    rerank: 'Reranking',
    featureApiTitle: 'One interface, switch models freely',
    featureRoutingTitle: 'Unlimited concurrency, always online',
    autoRoute: 'Auto routing',
    ecosystemTitle: 'Build a shared AI ecosystem',
    ecosystemSubtitle: 'Selected partner apps get 10% off every model. More integrations are coming.',
    partners: ['FineReport', 'Cherry Studio', 'HelpKnow', 'NextChat', 'LobeHub'],
    discountLine1: 'Get 10%',
    discountLine2: 'off',
    morePanels: [
      {
        title: 'Mainstream models in one place',
        text: 'OpenAI-compatible APIs for text, vision, audio, video, embeddings, reranking, and more.',
        link: 'View models',
      },
      {
        title: 'Stable routing, automatic fallback',
        text: 'Aggregate multiple upstream providers and route requests by availability and policy.',
        link: 'Open Playground',
      },
      {
        title: 'App ecosystem, ready to use',
        text: 'Connect popular clients and developer tools, and manage every scenario with one key.',
        link: 'Explore ecosystem',
      },
    ],
    footerTagline: 'One Interface, Router All Models.',
    notice: 'Notice',
  },
  fr: {
    heroAria: 'Page d\'accueil Kcode',
    heroTitle: 'Une API, des modeles illimites',
    heroSubtitle: 'Connectez les principaux modeles IA au meme endroit. Developpez plus vite et plus intelligemment.',
    docs: 'Docs',
    primaryCta: 'Commencer',
    featuresAria: 'Capacites principales',
    featureCoverageTitle: 'Couverture complete des modeles',
    voice: 'Generation vocale',
    video: 'Generation video',
    rerank: 'Reranking',
    featureApiTitle: 'Une interface, changez de modele librement',
    featureRoutingTitle: 'Concurrence illimitee, sans file d\'attente',
    autoRoute: 'Routage auto',
    ecosystemTitle: 'Construire un ecosysteme IA partage',
    ecosystemSubtitle: 'Des applications partenaires selectionnees profitent de 10% de reduction sur tous les modeles.',
    partners: ['FineReport', 'Cherry Studio', 'HelpKnow', 'NextChat', 'LobeHub'],
    discountLine1: '-10%',
    discountLine2: 'obtenir',
    morePanels: [
      {
        title: 'Modeles majeurs au meme endroit',
        text: 'API compatibles OpenAI pour texte, vision, audio, video, embeddings, reranking et plus.',
        link: 'Voir les modeles',
      },
      {
        title: 'Routage stable, bascule automatique',
        text: 'Agregez plusieurs fournisseurs upstream et routez selon disponibilite et strategie.',
        link: 'Ouvrir Playground',
      },
      {
        title: 'Ecosysteme applicatif pret a l\'emploi',
        text: 'Connectez clients et outils de developpement avec une seule cle pour tous les usages.',
        link: 'Explorer',
      },
    ],
    footerTagline: 'One Interface, Router All Models.',
    notice: 'Avis',
  },
  ja: {
    heroAria: 'Kcode ホームページ',
    heroTitle: '1つのAPIで、無限のモデルへ',
    heroSubtitle: '主要なAIモデルを一括接続。開発をよりスマートに、より高速に。',
    docs: 'ドキュメント',
    primaryCta: '今すぐ試す',
    featuresAria: '主な機能',
    featureCoverageTitle: 'モデルを幅広くカバー',
    voice: '音声生成',
    video: '動画生成',
    rerank: 'リランキング',
    featureApiTitle: '統一APIでモデルを簡単切替',
    featureRoutingTitle: '高並列でも待ち時間なし',
    autoRoute: '自動ルーティング',
    ecosystemTitle: 'AIエコシステムを共に構築',
    ecosystemSubtitle: '厳選パートナーアプリなら、全モデルを10%割引で利用できます。連携先は今後も追加予定です。',
    partners: ['FineReport', 'Cherry Studio', 'HelpKnow', 'NextChat', 'LobeHub'],
    discountLine1: '10%割引',
    discountLine2: 'を取得',
    morePanels: [
      {
        title: '主要モデルをまとめて接続',
        text: 'OpenAI互換APIで、テキスト、画像、音声、動画、埋め込み、リランキングに対応。',
        link: 'モデルを見る',
      },
      {
        title: '安定ルーティング、自動切替',
        text: '複数の上流プロバイダーを集約し、可用性とポリシーに応じて自動分散します。',
        link: 'Playgroundへ',
      },
      {
        title: 'アプリ連携、すぐに利用可能',
        text: '主要クライアントや開発ツールと接続し、1つのKeyで用途別のモデル利用を管理できます。',
        link: 'エコシステムを見る',
      },
    ],
    footerTagline: 'One Interface, Router All Models.',
    notice: 'お知らせ',
  },
  ru: {
    heroAria: 'Главная Kcode',
    heroTitle: 'Один API, неограниченные модели',
    heroSubtitle: 'Подключайте ведущие AI-модели в одном месте. Разрабатывайте быстрее и эффективнее.',
    docs: 'Документы',
    primaryCta: 'Начать',
    featuresAria: 'Ключевые возможности',
    featureCoverageTitle: 'Широкий охват моделей',
    voice: 'Генерация речи',
    video: 'Генерация видео',
    rerank: 'Реранжирование',
    featureApiTitle: 'Единый интерфейс для смены моделей',
    featureRoutingTitle: 'Высокая параллельность без очередей',
    autoRoute: 'Автороутинг',
    ecosystemTitle: 'Создаем общую AI-экосистему',
    ecosystemSubtitle: 'Избранные партнерские приложения получают скидку 10% на все модели. Интеграции продолжаются.',
    partners: ['FineReport', 'Cherry Studio', 'HelpKnow', 'NextChat', 'LobeHub'],
    discountLine1: 'Скидка 10%',
    discountLine2: 'получить',
    morePanels: [
      {
        title: 'Популярные модели в одном месте',
        text: 'OpenAI-совместимые API для текста, зрения, аудио, видео, эмбеддингов и реранжирования.',
        link: 'Смотреть модели',
      },
      {
        title: 'Стабильный роутинг и автофолбэк',
        text: 'Объединяйте несколько upstream-провайдеров и маршрутизируйте запросы по доступности и правилам.',
        link: 'Открыть Playground',
      },
      {
        title: 'Экосистема приложений готова',
        text: 'Подключайте популярные клиенты и инструменты разработки, управляя сценариями одним ключом.',
        link: 'Подробнее',
      },
    ],
    footerTagline: 'One Interface, Router All Models.',
    notice: 'Объявления',
  },
  vi: {
    heroAria: 'Trang chu Kcode',
    heroTitle: 'Mot API, vo han mo hinh',
    heroSubtitle: 'Ket noi cac mo hinh AI hang dau tai mot noi. Phat trien thong minh va nhanh hon.',
    docs: 'Tai lieu',
    primaryCta: 'Dung ngay',
    featuresAria: 'Nang luc cot loi',
    featureCoverageTitle: 'Bao phu day du mo hinh',
    voice: 'Tao giong noi',
    video: 'Tao video',
    rerank: 'Sap xep lai',
    featureApiTitle: 'Mot giao dien, doi mo hinh de dang',
    featureRoutingTitle: 'Dong thoi cao, khong phai cho',
    autoRoute: 'Dinh tuyen tu dong',
    ecosystemTitle: 'Xay dung he sinh thai AI cung thang',
    ecosystemSubtitle: 'Ung dung doi tac chon loc duoc giam 10% cho moi mo hinh. Nhieu tich hop se tiep tuc duoc bo sung.',
    partners: ['FineReport', 'Cherry Studio', 'HelpKnow', 'NextChat', 'LobeHub'],
    discountLine1: 'Nhan 10%',
    discountLine2: 'uu dai',
    morePanels: [
      {
        title: 'Mo hinh pho bien trong mot noi',
        text: 'API tuong thich OpenAI cho van ban, thi giac, am thanh, video, embedding, reranking va hon the nua.',
        link: 'Xem mo hinh',
      },
      {
        title: 'Dinh tuyen on dinh, tu dong chuyen doi',
        text: 'Tong hop nhieu nha cung cap upstream va phan phoi yeu cau theo kha dung va chien luoc.',
        link: 'Mo Playground',
      },
      {
        title: 'He sinh thai ung dung san sang',
        text: 'Ket noi cac client va cong cu phat trien pho bien, quan ly moi kich ban bang mot Key.',
        link: 'Tim hieu them',
      },
    ],
    footerTagline: 'One Interface, Router All Models.',
    notice: 'Thong bao',
  },
};

export const getHomeCopy = (language) => {
  const normalizedLanguage = normalizeLanguage(language) || 'zh-CN';
  return homeCopy[normalizedLanguage] || homeCopy['zh-CN'];
};
